### ISSUE TITLE
Back button on UI

### ISSUE THREAD

**Issue by Stackeduary** [QGasSP/ggia-frontend#12]
Is it possible to implement a back button on the UI so a user can go back one screen and choose different parameters?

**Comment by Onunda** [comment]
Instead of a back button, we had decided to add a nav bar at the top in the header next to the app name, with links to different parts. will push changes later after merging U2 to the main repo after the demo.

**Comment by Armin-Remenyi** [comment]
Bill found a little bug, if you click on "Back" then click on "Next" it takes you back. We will fix this later and actually implement the "Back" button to fit with our wireframe ideas.
