### ISSUE TITLE
Validation for Year and Country on Start Page

### ISSUE THREAD

**Issue by Stackeduary** [QGasSP/ggia-frontend#14]
Trying to generate the calculation without inputting a population generates a popup warning message, but not for Country or Year.

Need to add validation message for Country and Year and not allow user to proceed without choosing both fields.

**Comment by Onunda** [comment]
I did the full validation for all the inputs for the start page and sent the values to U1 for using in settlement type endpoint . I guess for the demo Kimmo can enter population value. I will alert him in discord.
